### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by christopherhesse** [cshesse/blobfile#5] opened 2019-10-23 22:18 UTC
File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/blobfile/blobfile.py", line 1031, in __init__
    resp, self._metadata = _gcs_get_blob_metadata(path)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/blobfile/blobfile.py", line 269, in _gcs_get_blob_metadata
    with _execute_request(req) as resp:
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/blobfile/blobfile.py", line 159, in _execute_request
    redirect=False,
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)

**Comment by cshesse** [comment] 2019-10-24 05:10
duplicate of https://github.com/cshesse/blobfile/issues/6

**Closed by cshesse** 2019-10-24 05:10 UTC
